-- app_user
CREATE TABLE APP_USER
(
    USER_NUM       bigserial PRIMARY KEY,
    USER_NAME      varchar(10),
    USER_GENDER    char,
    USER_MOBILE    varchar(20),
    USER_EMAIL     varchar(256),
    USER_PWD       varchar(256),
    USER_LINE_NAME varchar(40) NOT NULL,
    USER_LINE_ID   varchar(20) NOT NULL
        CONSTRAINT USER_ID_UNIQUE UNIQUE,
    USER_LINE_PIC  varchar(512)
);
COMMENT ON TABLE APP_USER IS '使用者記錄檔';
COMMENT ON COLUMN APP_USER.USER_NUM IS '使用者編號';
COMMENT ON COLUMN APP_USER.USER_NAME IS '使用者姓名';
COMMENT ON COLUMN APP_USER.USER_GENDER IS '使用者性別(1:男,2:女,3:不顯示)';
COMMENT ON COLUMN APP_USER.USER_MOBILE IS '使用者電話';
COMMENT ON COLUMN APP_USER.USER_EMAIL IS '使用者信箱';
COMMENT ON COLUMN APP_USER.USER_PWD IS '使用者密碼';
COMMENT ON COLUMN APP_USER.USER_LINE_NAME IS '使用者LINE名稱';
COMMENT ON COLUMN APP_USER.USER_LINE_ID IS '使用者LINE userId';
COMMENT ON COLUMN APP_USER.USER_LINE_PIC IS '使用者LINE照片路徑';

-- app_user_member_status
CREATE TABLE APP_USER_MEMBER_STATUS
(
    AUMS_NUM       bigserial PRIMARY KEY,
    USER_NUM       bigint    NOT NULL
        CONSTRAINT APP_USER_FK REFERENCES APP_USER,
    USER_STATUS    char      NOT NULL,
    CREATE_DATE    timestamp NOT NULL DEFAULT NOW(),
    FOLLOW_DATE    timestamp,
    UN_FOLLOW_DATE timestamp,
    UN_FOLLOW_TIME bigint    NOT NULL DEFAULT 0
);
COMMENT ON TABLE APP_USER_MEMBER_STATUS IS '使用者狀態紀錄檔';
COMMENT ON COLUMN APP_USER_MEMBER_STATUS.AUMS_NUM IS '狀態紀錄編號';
COMMENT ON COLUMN APP_USER_MEMBER_STATUS.USER_NUM IS '使用者編號';
COMMENT ON COLUMN APP_USER_MEMBER_STATUS.USER_STATUS IS '使用者狀態(1:使用中,0:已移除)';
COMMENT ON COLUMN APP_USER_MEMBER_STATUS.CREATE_DATE IS '建立日期';
COMMENT ON COLUMN APP_USER_MEMBER_STATUS.FOLLOW_DATE IS '追蹤日期';
COMMENT ON COLUMN APP_USER_MEMBER_STATUS.UN_FOLLOW_DATE IS '取消追蹤日期';
COMMENT ON COLUMN APP_USER_MEMBER_STATUS.UN_FOLLOW_TIME IS '取消追蹤次數';